In [1]:
import  pandas as pd
from datetime import datetime
import  numpy  as np

# DataFrame Final para el modelo

In [2]:
MAFI = pd.read_csv("Limp_MAFI.csv")
MAFI

Scoring = pd.read_csv("Limp_Scoring.csv")
Scoring

Credito = pd.read_csv("Limp_Credito_Cartera.csv")
Credito

,Llave,Llave2,Nombre_linea,Fecha_aprobacion,Antiguedad_meses,Nombre_fondo,Valor_financiacion,Cuotas,Tipo_interes,Vr_neto_matricula,Cuotas_vencidas,Cuotas__por_vencer,Y_continua,Y_categorica
0,100046415_202110,100046415_202110_13110,ESTUDIA YA-TECH GLOBAL,2021-02-12,56,BOGOTA,1895042,12,Cap. Fijo-Int. vencido,2190800.0,0,0,0.0,Bajo
1,100094861_202131,100094861_202131_13118,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,CONVENIO SENA NACIONAL,1312400,4,Cap. Fijo-Int. vencido,1544000.0,0,0,0.0,Bajo
2,100090085_202141,100090085_202141_13292,ESTUDIA YA-TECH GLOBAL LINEA BLANCA,2021-02-05,56,CONVENIO INESUR,2589525,4,Cap. Fijo-Int. vencido,3385000.0,0,0,0.0,Bajo
3,100082960_202131,100082960_202131_13165,ESTUDIA YA-TECH GLOBAL,2021-02-25,56,CONVENIO CONSTRUYENDO FUTURO - CONSFUTUR S.A.S,1307300,6,Cap. Fijo-Int. vencido,1538000.0,0,0,0.0,Bajo
4,100083999_202110,100083999_202110_13175,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,BOGOTA,2186720,6,Cap. Fijo-Int. vencido,2528000.0,0,0,0.0,Bajo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72300,100199663_202555,100199663_202555_92014,LINEA CRÉDITO CUOTA FIJO,2025-10-15,0,BOGOTA,3910538,4,Anualidad Vencida,4669633.0,0,4,0.0,Bajo
72301,100229719_202544,100229719_202544_90644,LINEA CRÉDITO CUOTA FIJO,2025-10-05,1,BOGOTA,2061160,4,Anualidad Vencida,2493895.0,0,4,0.0,Bajo
72302,100181306_202517,100181306_202517_92383,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,CONVENIO CIADET,1963387,4,Anualidad Vencida,2378868.0,0,4,0.0,Bajo
72303,100231814_202508,100231814_202508_92406,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,BOGOTA,1636250,6,Anualidad Vencida,1994000.0,0,6,0.0,Bajo
72304,100230402_202517,100230402_202517_91000,LINEA CRÉDITO CUOTA FIJO,2025-09-20,1,BOGOTA,1710515,6,Anualidad Vencida,2081371.0,0,6,0.0,Bajo

In [3]:
MAFI.columns, Scoring.columns, Credito.columns

(Index(['IDBANNER', 'FECHA_NACIMIENTO', 'ESTADO_CIVIL', 'DIRECCION', 'CIUDAD',
        'CODCIUDAD', 'GENERO', 'FACULTAD', 'PROGRAMA', 'NIVEL', 'PERIODO',
        'ESTADO', 'TIPOESTUDIANTE', 'SEDE', 'SELLO', 'CARGA', 'GRUPO_ETNICO',
        'TIPO_DISCAPACIDAD', 'NACIONALIDAD', 'Llave'],
       dtype='object'),
 Index(['Llave', 'fecha_creacion_transaccion', 'Mora', 'Valor_Matricula',
        'Valor_cuota_inicial', 'Valor_primera_cuota', 'fecha de pago',
        'Dirección_Scoring', 'Ciudad_Scoring', 'Departamento_Scoring',
        'Validación valor financiado', 'Detalle estado final', 'ID Estudiante',
        'Periodo', 'Tipo_estudiante', 'Operación', 'Cate', 'Subcate', 'Cohorte',
        'Mes', 'Cliente', 'Media Score', 'AñoB', 'VALOR MAXIMO', 'VALOR MEDIO',
        'VALOR BAJO', 'Plataforma'],
       dtype='object'),
 Index(['Llave', 'Llave2', 'Nombre_linea', 'Fecha_aprobacion',
        'Antiguedad_meses', 'Nombre_fondo', 'Valor_financiacion', 'Cuotas',
        'Tipo_interes', 'Vr_neto_matricula', 'Cuotas_vencidas',
        'Cuotas__por_vencer', 'Y_continua', 'Y_categorica'],
       dtype='object'))

In [4]:
df_inicial = Credito \
    .merge(MAFI, on='Llave', how='left') \
    .merge(Scoring, on='Llave', how='left')
df_inicial

,Llave,Llave2,Nombre_linea,Fecha_aprobacion,Antiguedad_meses,Nombre_fondo,Valor_financiacion,Cuotas,Tipo_interes,Vr_neto_matricula,...,Subcate,Cohorte,Mes,Cliente,Media Score,AñoB,VALOR MAXIMO,VALOR MEDIO,VALOR BAJO,Plataforma
0,100046415_202110,100046415_202110_13110,ESTUDIA YA-TECH GLOBAL,2021-02-12,56,BOGOTA,1895042,12,Cap. Fijo-Int. vencido,2190800.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 721,2021.0,0.0,0.0,0.0,ROMBO V1
1,100094861_202131,100094861_202131_13118,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,CONVENIO SENA NACIONAL,1312400,4,Cap. Fijo-Int. vencido,1544000.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 721,2021.0,0.0,0.0,0.0,ROMBO V1
2,100090085_202141,100090085_202141_13292,ESTUDIA YA-TECH GLOBAL LINEA BLANCA,2021-02-05,56,CONVENIO INESUR,2589525,4,Cap. Fijo-Int. vencido,3385000.0,...,Tiene Sello Financiero (Lista Blanca),Cohorte 1,Febrero,Estudiante,Scoring = o > 401 y < o = 480,2021.0,0.0,0.0,0.0,ROMBO V1
3,100082960_202131,100082960_202131_13165,ESTUDIA YA-TECH GLOBAL,2021-02-25,56,CONVENIO CONSTRUYENDO FUTURO - CONSFUTUR S.A.S,1307300,6,Cap. Fijo-Int. vencido,1538000.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 561 y < o = 639,2021.0,0.0,0.0,0.0,ROMBO V1
4,100083999_202110,100083999_202110_13175,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,BOGOTA,2186720,6,Cap. Fijo-Int. vencido,2528000.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 561 y < o = 639,2021.0,0.0,0.0,0.0,ROMBO V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72766,100199663_202555,100199663_202555_92014,LINEA CRÉDITO CUOTA FIJO,2025-10-15,0,BOGOTA,3910538,4,Anualidad Vencida,4669633.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Septiembre,No Estudiante,Scoring = o > 640 y < o = 720,2025.0,3773000.0,2903000.0,2032000.0,ROMBO V2
72767,100229719_202544,100229719_202544_90644,LINEA CRÉDITO CUOTA FIJO,2025-10-05,1,BOGOTA,2061160,4,Anualidad Vencida,2493895.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 4,Septiembre,Estudiante,Scoring = o > 721,2025.0,4496000.0,3459000.0,2421000.0,ROMBO V2
72768,100181306_202517,100181306_202517_92383,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,CONVENIO CIADET,1963387,4,Anualidad Vencida,2378868.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Octubre,No Estudiante,Scoring = o > 721,2025.0,4343000.0,3341000.0,2338000.0,ROMBO V2
72769,100231814_202508,100231814_202508_92406,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,BOGOTA,1636250,6,Anualidad Vencida,1994000.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Octubre,Estudiante,Scoring = o > 721,2025.0,3719000.0,2861000.0,2002000.0,ROMBO V2
72770,100230402_202517,100230402_202517_91000,LINEA CRÉDITO CUOTA FIJO,2025-09-20,1,BOGOTA,1710515,6,Anualidad Vencida,2081371.0,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Septiembre,No Estudiante,Scoring = o > 561 y < o = 639,2025.0,5088000.0,3914000.0,2739000.0,ROMBO V2

In [5]:
df_inicial.columns

Index(['Llave', 'Llave2', 'Nombre_linea', 'Fecha_aprobacion',
       'Antiguedad_meses', 'Nombre_fondo', 'Valor_financiacion', 'Cuotas',
       'Tipo_interes', 'Vr_neto_matricula', 'Cuotas_vencidas',
       'Cuotas__por_vencer', 'Y_continua', 'Y_categorica', 'IDBANNER',
       'FECHA_NACIMIENTO', 'ESTADO_CIVIL', 'DIRECCION', 'CIUDAD', 'CODCIUDAD',
       'GENERO', 'FACULTAD', 'PROGRAMA', 'NIVEL', 'PERIODO', 'ESTADO',
       'TIPOESTUDIANTE', 'SEDE', 'SELLO', 'CARGA', 'GRUPO_ETNICO',
       'TIPO_DISCAPACIDAD', 'NACIONALIDAD', 'fecha_creacion_transaccion',
       'Mora', 'Valor_Matricula', 'Valor_cuota_inicial', 'Valor_primera_cuota',
       'fecha de pago', 'Dirección_Scoring', 'Ciudad_Scoring',
       'Departamento_Scoring', 'Validación valor financiado',
       'Detalle estado final', 'ID Estudiante', 'Periodo', 'Tipo_estudiante',
       'Operación', 'Cate', 'Subcate', 'Cohorte', 'Mes', 'Cliente',
       'Media Score', 'AñoB', 'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO',
       'Plataforma'],
      dtype='object')

In [6]:
#eliminamos filas con IDBANNER o ID Estudiante nulos
df_inicial = df_inicial[df_inicial['IDBANNER'].notnull()]
df_inicial = df_inicial[df_inicial['ID Estudiante'].notnull()]

In [7]:
df_inicial.isna().sum()[df_inicial.isna().sum() > 0]

DIRECCION                147
CIUDAD                  2144
CODCIUDAD                 23
Dirección_Scoring       3024
Ciudad_Scoring            40
Departamento_Scoring      59
dtype: int64

In [8]:
#quitamos columnas con vacios para el modelo dada la diferencia entre el dataset de 
# scoring (tomador del crédito) con el de MAFI (estudiante)
# Dejamos las columnas que pueden ser útiles para el análisis de morosidad

columnas_modelo = ['Llave2', 'Nombre_linea', 'Fecha_aprobacion',
       'Antiguedad_meses', 'Nombre_fondo', 'Valor_financiacion', 'Cuotas',
       'Tipo_interes', 'Vr_neto_matricula', 'Y_categorica', 'IDBANNER',
       'FECHA_NACIMIENTO', 'ESTADO_CIVIL',
       'GENERO', 'FACULTAD', 'PROGRAMA', 'NIVEL', 'ESTADO',
       'TIPOESTUDIANTE', 'SEDE', 'SELLO', 'CARGA', 'GRUPO_ETNICO',
       'TIPO_DISCAPACIDAD', 'NACIONALIDAD',
       'Mora', 'Valor_cuota_inicial', 'Valor_primera_cuota',
       'fecha de pago','Validación valor financiado',
       'Detalle estado final', 'Tipo_estudiante',
       'Operación', 'Cate', 'Subcate', 'Cohorte', 'Mes', 'Cliente',
       'Media Score', 'AñoB', 'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO',
       'Plataforma']


df_modelo= df_inicial[columnas_modelo].copy()

df_modelo
df_modelo.isna().sum()[df_modelo.isna().sum() > 0]

Series([], dtype: int64)

In [9]:
df_modelo.to_csv('df_modelo.csv', index=False, encoding='utf-8-sig')

In [10]:
# Lista de columnas finales
columnas_finales = ['Llave2', 'Nombre_linea', 'Fecha_aprobacion',
       'Antiguedad_meses', 'Nombre_fondo', 'Valor_financiacion', 'Cuotas',
       'Tipo_interes', 'Vr_neto_matricula', 'Y_categorica', 'IDBANNER',
       'FECHA_NACIMIENTO', 'ESTADO_CIVIL', 'DIRECCION', 'CIUDAD', 'CODCIUDAD',
       'GENERO', 'FACULTAD', 'PROGRAMA', 'NIVEL', 'ESTADO',
       'TIPOESTUDIANTE', 'SEDE', 'SELLO', 'CARGA', 'GRUPO_ETNICO',
       'TIPO_DISCAPACIDAD', 'NACIONALIDAD',
       'Mora', 'Valor_cuota_inicial', 'Valor_primera_cuota',
       'fecha de pago', 'Dirección_Scoring', 'Ciudad_Scoring',
       'Departamento_Scoring', 'Validación valor financiado',
       'Detalle estado final', 'ID Estudiante', 'Tipo_estudiante',
       'Operación', 'Cate', 'Subcate', 'Cohorte', 'Mes', 'Cliente',
       'Media Score', 'AñoB', 'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO',
       'Plataforma']


df_final= df_inicial[columnas_finales].copy()

df_final

,Llave2,Nombre_linea,Fecha_aprobacion,Antiguedad_meses,Nombre_fondo,Valor_financiacion,Cuotas,Tipo_interes,Vr_neto_matricula,Y_categorica,...,Subcate,Cohorte,Mes,Cliente,Media Score,AñoB,VALOR MAXIMO,VALOR MEDIO,VALOR BAJO,Plataforma
0,100046415_202110_13110,ESTUDIA YA-TECH GLOBAL,2021-02-12,56,BOGOTA,1895042,12,Cap. Fijo-Int. vencido,2190800.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 721,2021.0,0.0,0.0,0.0,ROMBO V1
1,100094861_202131_13118,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,CONVENIO SENA NACIONAL,1312400,4,Cap. Fijo-Int. vencido,1544000.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 721,2021.0,0.0,0.0,0.0,ROMBO V1
2,100090085_202141_13292,ESTUDIA YA-TECH GLOBAL LINEA BLANCA,2021-02-05,56,CONVENIO INESUR,2589525,4,Cap. Fijo-Int. vencido,3385000.0,Bajo,...,Tiene Sello Financiero (Lista Blanca),Cohorte 1,Febrero,Estudiante,Scoring = o > 401 y < o = 480,2021.0,0.0,0.0,0.0,ROMBO V1
3,100082960_202131_13165,ESTUDIA YA-TECH GLOBAL,2021-02-25,56,CONVENIO CONSTRUYENDO FUTURO - CONSFUTUR S.A.S,1307300,6,Cap. Fijo-Int. vencido,1538000.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 561 y < o = 639,2021.0,0.0,0.0,0.0,ROMBO V1
4,100083999_202110_13175,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,BOGOTA,2186720,6,Cap. Fijo-Int. vencido,2528000.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 1,Febrero,Estudiante,Scoring = o > 561 y < o = 639,2021.0,0.0,0.0,0.0,ROMBO V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72766,100199663_202555_92014,LINEA CRÉDITO CUOTA FIJO,2025-10-15,0,BOGOTA,3910538,4,Anualidad Vencida,4669633.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Septiembre,No Estudiante,Scoring = o > 640 y < o = 720,2025.0,3773000.0,2903000.0,2032000.0,ROMBO V2
72767,100229719_202544_90644,LINEA CRÉDITO CUOTA FIJO,2025-10-05,1,BOGOTA,2061160,4,Anualidad Vencida,2493895.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 4,Septiembre,Estudiante,Scoring = o > 721,2025.0,4496000.0,3459000.0,2421000.0,ROMBO V2
72768,100181306_202517_92383,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,CONVENIO CIADET,1963387,4,Anualidad Vencida,2378868.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Octubre,No Estudiante,Scoring = o > 721,2025.0,4343000.0,3341000.0,2338000.0,ROMBO V2
72769,100231814_202508_92406,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,BOGOTA,1636250,6,Anualidad Vencida,1994000.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Octubre,Estudiante,Scoring = o > 721,2025.0,3719000.0,2861000.0,2002000.0,ROMBO V2
72770,100230402_202517_91000,LINEA CRÉDITO CUOTA FIJO,2025-09-20,1,BOGOTA,1710515,6,Anualidad Vencida,2081371.0,Bajo,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Septiembre,No Estudiante,Scoring = o > 561 y < o = 639,2025.0,5088000.0,3914000.0,2739000.0,ROMBO V2

In [11]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72292 entries, 0 to 72770
Data columns (total 51 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Llave2                       72292 non-null  object
 1   Nombre_linea                 72292 non-null  object
 2   Fecha_aprobacion             72292 non-null  object
 3   Antiguedad_meses             72292 non-null  int64
 4   Nombre_fondo                 72292 non-null  object
 5   Valor_financiacion           72292 non-null  int64
 6   Cuotas                       72292 non-null  int64
 7   Tipo_interes                 72292 non-null  object
 8   Vr_neto_matricula            72292 non-null  float64
 9   Y_categorica                 72292 non-null  object
 10  IDBANNER                     72292 non-null  float64
 11  FECHA_NACIMIENTO             72292 non-null  object
 12  ESTADO_CIVIL                 72292 non-null  object
 13  DIRECCION                    72145 non-null  object
 14  CIUDAD                       70148 non-null  object
 15  CODCIUDAD                    72269 non-null  float64
 16  GENERO                       72292 non-null  object
 17  FACULTAD                     72292 non-null  object
 18  PROGRAMA                     72292 non-null  object
 19  NIVEL                        72292 non-null  object
 20  ESTADO                       72292 non-null  object
 21  TIPOESTUDIANTE               72292 non-null  object
 22  SEDE                         72292 non-null  object
 23  SELLO                        72292 non-null  object
 24  CARGA                        72292 non-null  object
 25  GRUPO_ETNICO                 72292 non-null  object
 26  TIPO_DISCAPACIDAD            72292 non-null  object
 27  NACIONALIDAD                 72292 non-null  object
 28  Mora                         72292 non-null  object
 29  Valor_cuota_inicial          72292 non-null  float64
 30  Valor_primera_cuota          72292 non-null  float64
 31  fecha de pago                72292 non-null  float64
 32  Dirección_Scoring            69268 non-null  object
 33  Ciudad_Scoring               72252 non-null  object
 34  Departamento_Scoring         72233 non-null  object
 35  Validación valor financiado  72292 non-null  float64
 36  Detalle estado final         72292 non-null  object
 37  ID Estudiante                72292 non-null  float64
 38  Tipo_estudiante              72292 non-null  object
 39  Operación                    72292 non-null  object
 40  Cate                         72292 non-null  object
 41  Subcate                      72292 non-null  object
 42  Cohorte                      72292 non-null  object
 43  Mes                          72292 non-null  object
 44  Cliente                      72292 non-null  object
 45  Media Score                  72292 non-null  object
 46  AñoB                         72292 non-null  float64
 47  VALOR MAXIMO                 72292 non-null  float64
 48  VALOR MEDIO                  72292 non-null  float64
 49  VALOR BAJO                   72292 non-null  float64
 50  Plataforma                   72292 non-null  object
dtypes: float64(12), int64(3), object(36)
memory usage: 28.7+ MB

In [12]:
#eliminamos filas con IDBANNER o ID Estudiante nulos
df_final = df_final[df_final['IDBANNER'].notnull()]
df_final = df_final[df_final['ID Estudiante'].notnull()]

In [13]:
#Diferencias en las dos columnas de direcciones
df_final[['DIRECCION', 'Dirección_Scoring']].isnull().sum()

DIRECCION             147
Dirección_Scoring    3024
dtype: int64

In [14]:
#Imputamos entre ellas
df_final['DIRECCION'] = df_final['DIRECCION'].fillna(df_final['Dirección_Scoring'])
df_final['DIRECCION'].isnull().sum()

np.int64(26)

In [15]:
#Llenamos los valores faltantes restantes con 'NO REGISTRADA'
df_final['DIRECCION']= df_final['DIRECCION'].fillna('NO REGISTRADA')
df_final['DIRECCION'].isnull().sum()

np.int64(0)

In [16]:
#Lo eliminamos del dataframe final
df_final.drop(columns=['Dirección_Scoring'], inplace=True)
df_final.columns

Index(['Llave2', 'Nombre_linea', 'Fecha_aprobacion', 'Antiguedad_meses',
       'Nombre_fondo', 'Valor_financiacion', 'Cuotas', 'Tipo_interes',
       'Vr_neto_matricula', 'Y_categorica', 'IDBANNER', 'FECHA_NACIMIENTO',
       'ESTADO_CIVIL', 'DIRECCION', 'CIUDAD', 'CODCIUDAD', 'GENERO',
       'FACULTAD', 'PROGRAMA', 'NIVEL', 'ESTADO', 'TIPOESTUDIANTE', 'SEDE',
       'SELLO', 'CARGA', 'GRUPO_ETNICO', 'TIPO_DISCAPACIDAD', 'NACIONALIDAD',
       'Mora', 'Valor_cuota_inicial', 'Valor_primera_cuota', 'fecha de pago',
       'Ciudad_Scoring', 'Departamento_Scoring', 'Validación valor financiado',
       'Detalle estado final', 'ID Estudiante', 'Tipo_estudiante', 'Operación',
       'Cate', 'Subcate', 'Cohorte', 'Mes', 'Cliente', 'Media Score', 'AñoB',
       'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO', 'Plataforma'],
      dtype='object')

In [17]:
#Diferencias en las dos columnas de ciudades
df_final[['CIUDAD', 'Ciudad_Scoring']].isnull().sum()

CIUDAD            2144
Ciudad_Scoring      40
dtype: int64

In [18]:
#Imputamos entre ellas
df_final['CIUDAD'] = df_final['CIUDAD'].fillna(df_final['Ciudad_Scoring'])
df_final['CIUDAD'].isnull().sum()

np.int64(2)

In [19]:
mapa_codciu = (
    df_final[['CODCIUDAD', 'CIUDAD']]
    .dropna()
    .drop_duplicates(subset=['CODCIUDAD'])
    .set_index('CODCIUDAD')['CIUDAD']
)

In [20]:
#Imputamos los valores faltantes restantes usando el CODCIUDAD
df_final.loc[df_final['CIUDAD'].isnull(), 'CIUDAD'] = \
    df_final.loc[df_final['CIUDAD'].isnull(), 'CODCIUDAD'].map(mapa_codciu)

In [21]:
df_final['CIUDAD'].isnull().sum()

np.int64(0)

In [22]:
df_final['CODCIUDAD'].isnull().sum()

np.int64(23)

In [23]:
ciudades_sin_codigo = df_final.loc[df_final['CODCIUDAD'].isnull(), 'CIUDAD'].unique()
map_ciudad_cod = (
    df_final[['CIUDAD', 'CODCIUDAD']]
    .dropna()
    .drop_duplicates()
    .set_index('CIUDAD')['CODCIUDAD']
    .to_dict()
)

In [24]:
#imputamos los valores faltantes de CODCIUDAD usando CIUDAD
df_final['CODCIUDAD'] = df_final['CODCIUDAD'].fillna(
    df_final['CIUDAD'].map(map_ciudad_cod))

In [25]:
df_final['CODCIUDAD'].isnull().sum()

np.int64(9)

In [26]:
df_nulos_codigo= df_final[
    df_final["CODCIUDAD"].isnull()]

df_nulos_codigo = df_nulos_codigo[ 
    ["NACIONALIDAD", "CODCIUDAD", 
     "CIUDAD"]]

df_nulos_codigo

      NACIONALIDAD  CODCIUDAD   CIUDAD
5975      COLOMBIA        NaN    Girón
8587      COLOMBIA        NaN    Girón
8903      COLOMBIA        NaN    Girón
10846     COLOMBIA        NaN    Girón
20484     COLOMBIA        NaN  Zipacón
22416     COLOMBIA        NaN    Girón
24642     COLOMBIA        NaN    Girón
45002     COLOMBIA        NaN  Zipacón
54591     COLOMBIA        NaN    Girón

In [27]:
#Cargamos el archivo DIVIPOLA para hacer la imputación 
Divipola = pd.read_excel('DIVIPOLA_Municipios.xlsx')
Divipola

,Código_dep,Nombre_dep,Código _mun,Nombre_mun,Municipio,Longitud,Latitud,Nota
0,05,ANTIOQUIA,5001.0,MEDELLÍN,Municipio,-75.581775,6.246631,NaN
1,05,ANTIOQUIA,5002.0,ABEJORRAL,Municipio,-75.428739,5.789315,NaN
2,05,ANTIOQUIA,5004.0,ABRIAQUÍ,Municipio,-76.064304,6.632282,NaN
3,05,ANTIOQUIA,5021.0,ALEJANDRÍA,Municipio,-75.141346,6.376061,NaN
4,05,ANTIOQUIA,5030.0,AMAGÁ,Municipio,-75.702188,6.038708,NaN
...,...,...,...,...,...,...,...,...
1127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1131,** La cabecera municipal de San Andrés corresp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# Normalizar nombres
df_final['CIUDAD_norm'] = df_final['CIUDAD'].str.upper().str.strip()
Divipola['Nombre_mun_norm'] = Divipola['Nombre_mun'].str.upper().str.strip()

In [29]:
Divipola.columns

Index(['Código_dep', 'Nombre_dep', 'Código _mun', 'Nombre_mun', 'Municipio',
       'Longitud', 'Latitud', 'Nota', 'Nombre_mun_norm'],
      dtype='object')

In [30]:
map_divipola = (
    Divipola[['Nombre_mun_norm', 'Código _mun']]
    .dropna()
    .drop_duplicates()
    .set_index('Nombre_mun_norm')['Código _mun']
    .to_dict())

In [31]:
#imputamos los valores faltantes de CODCIUDAD usando CIUDAD del DIVIPOLA
df_final['CODCIUDAD'] = df_final['CODCIUDAD'].fillna(
    df_final['CIUDAD_norm'].map(map_divipola))

In [32]:
df_final['CODCIUDAD'].isnull().sum()

np.int64(0)

In [33]:
df_final.isnull().sum()[df_final.isnull().sum() > 0]

Ciudad_Scoring          40
Departamento_Scoring    59
dtype: int64

In [34]:
#agregamos el nombre del departamento usando el DIVIPOLA
df_final = df_final.merge(
    Divipola[["Código _mun", "Nombre_dep"]],
    left_on="CODCIUDAD",
    right_on="Código _mun",
    how="left")

In [35]:
#Imputamos los valores faltantes de Departamento_Scoring usando Nombre_dep
df_final['Departamento']=df_final["Departamento_Scoring"] = (
    df_final["Departamento_Scoring"]
    .fillna(df_final["Nombre_dep"]))

In [36]:
df_final["Departamento"].isnull().sum()

np.int64(0)

In [37]:
df_final = df_final.drop(columns=["Nombre_dep", "Ciudad_Scoring"])
df_final.columns

Index(['Llave2', 'Nombre_linea', 'Fecha_aprobacion', 'Antiguedad_meses',
       'Nombre_fondo', 'Valor_financiacion', 'Cuotas', 'Tipo_interes',
       'Vr_neto_matricula', 'Y_categorica', 'IDBANNER', 'FECHA_NACIMIENTO',
       'ESTADO_CIVIL', 'DIRECCION', 'CIUDAD', 'CODCIUDAD', 'GENERO',
       'FACULTAD', 'PROGRAMA', 'NIVEL', 'ESTADO', 'TIPOESTUDIANTE', 'SEDE',
       'SELLO', 'CARGA', 'GRUPO_ETNICO', 'TIPO_DISCAPACIDAD', 'NACIONALIDAD',
       'Mora', 'Valor_cuota_inicial', 'Valor_primera_cuota', 'fecha de pago',
       'Departamento_Scoring', 'Validación valor financiado',
       'Detalle estado final', 'ID Estudiante', 'Tipo_estudiante', 'Operación',
       'Cate', 'Subcate', 'Cohorte', 'Mes', 'Cliente', 'Media Score', 'AñoB',
       'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO', 'Plataforma',
       'CIUDAD_norm', 'Código _mun', 'Departamento'],
      dtype='object')

In [38]:
#agregamos Longitud y Latitud usando el DIVIPOLA
df_final = df_final.merge(
    Divipola[['Código _mun', 'Longitud', 'Latitud']],
    how='left',
    left_on='Código _mun',
    right_on='Código _mun')
df_final[['Longitud', 'Latitud']].isnull().sum()

Longitud    360
Latitud     360
dtype: int64

In [39]:
#Identificamos las ciudades que aún no tienen Longitud y Latitud
ciudades_sin_geo = df_final.loc[df_final['Longitud'].isnull(), 'CIUDAD_norm'].unique()
ciudades_sin_geo

array(['BELEN DE BAJIRA'], dtype=object)

In [40]:
#Revisamos la base de DIVIPOLA manual para ver si hay errores y corregímos
correcciones = {
    'BELEN DE BAJIRA': 'NUEVO BELÉN DE BAJIRÁ'}

df_final['CIUDAD_norm'] = df_final['CIUDAD_norm'].replace(correcciones)

In [41]:
df_final['Código _mun'].isnull().sum()

np.int64(360)

In [42]:
#Identificamos las filas con Código _mun faltante
faltantes = df_final[df_final['Código _mun'].isnull()][['CIUDAD_norm']]
faltantes_merge = faltantes.merge(
    Divipola[['Nombre_mun', 'Código _mun', 'Longitud', 'Latitud']],
    how='left',
    left_on='CIUDAD_norm',
    right_on='Nombre_mun')

In [43]:
#Imputamos los valores faltantes de Código _mun, Longitud y Latitud
df_final.loc[df_final['Código _mun'].isnull(), 'Código _mun'] = faltantes_merge['Código _mun'].values
df_final.loc[df_final['Longitud'].isnull(), 'Longitud'] = faltantes_merge['Longitud'].values
df_final.loc[df_final['Latitud'].isnull(), 'Latitud'] = faltantes_merge['Latitud'].values

In [44]:
df_final[['Código _mun', 'Longitud', 'Latitud']].isnull().sum()

Código _mun    0
Longitud       0
Latitud        0
dtype: int64

In [45]:
#limpiamos el dataframe final del modelo
df_final = df_final.drop(columns=['IDBANNER','Departamento_Scoring','CIUDAD', 'CODCIUDAD'])
df_final = df_final.reset_index(drop=True)
df_final.columns

Index(['Llave2', 'Nombre_linea', 'Fecha_aprobacion', 'Antiguedad_meses',
       'Nombre_fondo', 'Valor_financiacion', 'Cuotas', 'Tipo_interes',
       'Vr_neto_matricula', 'Y_categorica', 'FECHA_NACIMIENTO', 'ESTADO_CIVIL',
       'DIRECCION', 'GENERO', 'FACULTAD', 'PROGRAMA', 'NIVEL', 'ESTADO',
       'TIPOESTUDIANTE', 'SEDE', 'SELLO', 'CARGA', 'GRUPO_ETNICO',
       'TIPO_DISCAPACIDAD', 'NACIONALIDAD', 'Mora', 'Valor_cuota_inicial',
       'Valor_primera_cuota', 'fecha de pago', 'Validación valor financiado',
       'Detalle estado final', 'ID Estudiante', 'Tipo_estudiante', 'Operación',
       'Cate', 'Subcate', 'Cohorte', 'Mes', 'Cliente', 'Media Score', 'AñoB',
       'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO', 'Plataforma',
       'CIUDAD_norm', 'Código _mun', 'Departamento', 'Longitud', 'Latitud'],
      dtype='object')

In [46]:
#final revisión de nulos 
df_final.isnull().sum()[df_final.isnull().sum() > 0]

Series([], dtype: int64)

In [47]:
#Estandarizamos los nombres de las columnas
import unicodedata

def estandarizar_columna(col):
    col = unicodedata.normalize('NFKD', col).encode('ascii', 'ignore').decode('utf-8')
    col = col.lower()
    col = col.replace(" ", "_")
    col = col.replace("-", "_").replace("/", "_")
    col = "_".join(part for part in col.split("_") if part)
    return col
df_final.columns = [estandarizar_columna(col) for col in df_final.columns]

In [48]:
df_final

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,anob,valor_maximo,valor_medio,valor_bajo,plataforma,ciudad_norm,codigo_mun,departamento,longitud,latitud
0,100046415_202110_13110,ESTUDIA YA-TECH GLOBAL,2021-02-12,56,BOGOTA,1895042,12,Cap. Fijo-Int. vencido,2190800.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,"BOGOTA, D.C.",11001.0,"Bogotá, D.C.",-74.106992,4.649251
1,100094861_202131_13118,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,CONVENIO SENA NACIONAL,1312400,4,Cap. Fijo-Int. vencido,1544000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,MONTELIBANO,23466.0,Córdoba,-75.416818,7.973777
2,100090085_202141_13292,ESTUDIA YA-TECH GLOBAL LINEA BLANCA,2021-02-05,56,CONVENIO INESUR,2589525,4,Cap. Fijo-Int. vencido,3385000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,MOCOA,86001.0,Putumayo,-76.654238,1.151172
3,100082960_202131_13165,ESTUDIA YA-TECH GLOBAL,2021-02-25,56,CONVENIO CONSTRUYENDO FUTURO - CONSFUTUR S.A.S,1307300,6,Cap. Fijo-Int. vencido,1538000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,LA DORADA,17380.0,Cundinamarca,-74.668819,5.460834
4,100083999_202110_13175,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,BOGOTA,2186720,6,Cap. Fijo-Int. vencido,2528000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,"BOGOTA, D.C.",11001.0,"Bogotá, D.C.",-74.106992,4.649251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72611,100199663_202555_92014,LINEA CRÉDITO CUOTA FIJO,2025-10-15,0,BOGOTA,3910538,4,Anualidad Vencida,4669633.0,Bajo,...,2025.0,3773000.0,2903000.0,2032000.0,ROMBO V2,QUIBDO,27001.0,Chocó,-76.638144,5.682166
72612,100229719_202544_90644,LINEA CRÉDITO CUOTA FIJO,2025-10-05,1,BOGOTA,2061160,4,Anualidad Vencida,2493895.0,Bajo,...,2025.0,4496000.0,3459000.0,2421000.0,ROMBO V2,EL CERRITO,76248.0,Valle del Cauca,-76.311972,3.684229
72613,100181306_202517_92383,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,CONVENIO CIADET,1963387,4,Anualidad Vencida,2378868.0,Bajo,...,2025.0,4343000.0,3341000.0,2338000.0,ROMBO V2,JAMUNDI,76364.0,Valle del Cauca,-76.538472,3.258751
72614,100231814_202508_92406,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,BOGOTA,1636250,6,Anualidad Vencida,1994000.0,Bajo,...,2025.0,3719000.0,2861000.0,2002000.0,ROMBO V2,ITAGUI,5360.0,Antioquia,-75.612056,6.175079
72615,100230402_202517_91000,LINEA CRÉDITO CUOTA FIJO,2025-09-20,1,BOGOTA,1710515,6,Anualidad Vencida,2081371.0,Bajo,...,2025.0,5088000.0,3914000.0,2739000.0,ROMBO V2,SANTA ROSA DE CABAL,66682.0,Tolima,-75.623268,4.876271

In [49]:
df_final.columns

Index(['llave2', 'nombre_linea', 'fecha_aprobacion', 'antiguedad_meses',
       'nombre_fondo', 'valor_financiacion', 'cuotas', 'tipo_interes',
       'vr_neto_matricula', 'y_categorica', 'fecha_nacimiento', 'estado_civil',
       'direccion', 'genero', 'facultad', 'programa', 'nivel', 'estado',
       'tipoestudiante', 'sede', 'sello', 'carga', 'grupo_etnico',
       'tipo_discapacidad', 'nacionalidad', 'mora', 'valor_cuota_inicial',
       'valor_primera_cuota', 'fecha_de_pago', 'validacion_valor_financiado',
       'detalle_estado_final', 'id_estudiante', 'tipo_estudiante', 'operacion',
       'cate', 'subcate', 'cohorte', 'mes', 'cliente', 'media_score', 'anob',
       'valor_maximo', 'valor_medio', 'valor_bajo', 'plataforma',
       'ciudad_norm', 'codigo_mun', 'departamento', 'longitud', 'latitud'],
      dtype='object')

In [50]:
df_alto = df_final[df_final["y_categorica"].str.upper() == "ALTO"]
df_alto

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,anob,valor_maximo,valor_medio,valor_bajo,plataforma,ciudad_norm,codigo_mun,departamento,longitud,latitud
83,100069806_202117_15795,ESTUDIA YA-TECH GLOBAL,2021-09-20,49,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,2021.0,0.0,0.0,0.0,ROMBO V1,GIRARDOT,25307.0,Cundinamarca,-74.798201,4.313069
89,100118471_202211_18809,ESTUDIA YA-TECH GLOBAL PROMO NAVIDEÑA,2022-02-28,44,BOGOTA,1912840,6,Cap. Fijo-Int. vencido,2360000.0,Alto,...,2022.0,0.0,0.0,0.0,ROMBO V1,ARAUCA,81001.0,Arauca,-70.747408,7.072726
117,100098962_202210_18391,ESTUDIA YA-TECH GLOBAL PROMO NAVIDEÑA,2022-02-15,44,CONVENIO SENA NACIONAL,2292280,12,Cap. Fijo-Int. vencido,2736800.0,Alto,...,2022.0,0.0,0.0,0.0,ROMBO V1,SOACHA,25754.0,Cundinamarca,-74.215463,4.579268
150,100113934_202231_17568,ESTUDIA YA-TECH GLOBAL PROMO NAVIDEÑA,2022-02-05,45,CONVENIO PROFIN,1602483,6,Cap. Fijo-Int. vencido,1925275.0,Alto,...,2022.0,0.0,0.0,0.0,ROMBO V1,MAICAO,44430.0,La Guajira,-72.242738,11.378535
153,100108470_202117_16303,ESTUDIA YA-TECH GLOBAL NUEVA MODALIDAD,2021-11-05,48,CONVENIO SENA BOGOTA,1522307,6,Cap. Fijo-Int. vencido,1830950.0,Alto,...,2021.0,0.0,0.0,0.0,ROMBO V1,"BOGOTA, D.C.",11001.0,"Bogotá, D.C.",-74.106992,4.649251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72520,100118952_202534_88826,LINEA CRÉDITO CUOTA FIJO,2025-08-20,2,BOGOTA,2421841,12,Anualidad Vencida,2918225.0,Alto,...,2025.0,0.0,0.0,0.0,ROMBO V2,FACATATIVA,25269.0,Cundinamarca,-74.350085,4.813353
72521,100036813_202534_86830,LINEA CRÉDITO CUOTA FIJO,2025-08-05,3,EDUPOL,1209679,12,Anualidad Vencida,2102075.0,Alto,...,2025.0,10400000.0,8000000.0,5600000.0,ROMBO V2,SIBUNDOY,86749.0,Huila,-76.917814,1.200260
72523,100175663_202520_87804,LINEA CRÉDITO CUOTA FIJO,2025-08-20,2,BOGOTA,4165000,4,Anualidad Vencida,7069000.0,Alto,...,2025.0,2298000.0,1768000.0,1237000.0,ROMBO V2,"BOGOTA, D.C.",11001.0,Bogotá D.C.,-74.106992,4.649251
72524,100225550_202554_86714,LINEA CRÉDITO CUOTA FIJO,2025-08-20,2,BOGOTA,4041139,6,Anualidad Vencida,4823282.0,Alto,...,2025.0,2609000.0,2007000.0,1404000.0,ROMBO V2,MONTERIA,23001.0,Bogotá D.C.,-75.873096,8.759789
72531,100181050_202520_86365,LINEA CRÉDITO CUOTA FIJO,2025-08-20,2,BOGOTA,2200667,6,Anualidad Vencida,3767600.0,Alto,...,2025.0,2839000.0,2184000.0,1528000.0,ROMBO V2,"BOGOTA, D.C.",11001.0,Bogotá D.C.,-74.106992,4.649251

In [51]:
llave_objetivo = "100069806_202117_15795"

fila = df_final[df_final["llave2"] == llave_objetivo]

print("Registros encontrados:", len(fila))
display(fila.T)   # Mostrar columnas y valores de forma vertical

Registros encontrados: 1

                                                                    83
llave2                                          100069806_202117_15795
nombre_linea                                    ESTUDIA YA-TECH GLOBAL
fecha_aprobacion                                            2021-09-20
antiguedad_meses                                                    49
nombre_fondo                                                    BOGOTA
valor_financiacion                                             1569993
cuotas                                                               6
tipo_interes                                    Cap. Fijo-Int. vencido
vr_neto_matricula                                            2173000.0
y_categorica                                                      Alto
fecha_nacimiento                                            1996-03-04
estado_civil                                               SOLTERO (A)
direccion                                          MANZANA E3 # 4M - 4
genero                                                               F
facultad                                FACULTAD DE CCIAS HUMANAS SOCI
programa                                            PSICOLOGIA VIRTUAL
nivel                                                      PROFESIONAL
estado                                                          Activo
tipoestudiante                                          PRIMER INGRESO
sede                                                               VIR
sello                                           TIENE SELLO FINANCIERO
carga                                                   0 A 999999.999
grupo_etnico                                              NO PERTENECE
tipo_discapacidad                                            NO APLICA
nacionalidad                                                  COLOMBIA
mora                                                             False
valor_cuota_inicial                                           277057.5
valor_primera_cuota                                      291181.275667
fecha_de_pago                                                     20.0
validacion_valor_financiado                              162232.558333
detalle_estado_final                                      Desembolsado
id_estudiante                                              100069806.0
tipo_estudiante                                       Estudiante Nuevo
operacion                                                      Contact
cate                                                  Sello Financiero
subcate                      Tiene Sello Financiero (Aprobado Directo)
cohorte                                                      Cohorte 5
mes                                                         Septiembre
cliente                                                     Estudiante
media_score                             Scoring = o > 640  y < o = 720
anob                                                            2021.0
valor_maximo                                                       0.0
valor_medio                                                        0.0
valor_bajo                                                         0.0
plataforma                                                    ROMBO V1
ciudad_norm                                                   GIRARDOT
codigo_mun                                                     25307.0
departamento                                              Cundinamarca
longitud                                                    -74.798201
latitud                                                       4.313069

In [52]:
llave_objetivo = "100069806_202117_15795"

fila_original = df_final[df_final["llave2"] == llave_objetivo].copy()
fila_original

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,anob,valor_maximo,valor_medio,valor_bajo,plataforma,ciudad_norm,codigo_mun,departamento,longitud,latitud
83,100069806_202117_15795,ESTUDIA YA-TECH GLOBAL,2021-09-20,49,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,2021.0,0.0,0.0,0.0,ROMBO V1,GIRARDOT,25307.0,Cundinamarca,-74.798201,4.313069

In [53]:
from datetime import datetime

hoy = datetime.today()

nuevo = fila_original.copy()

# Cambios solicitados
nuevo["fecha_aprobacion"] = hoy.strftime("%Y-%m-%d")
nuevo["id_estudiante"] = "00000"

# Crear nueva llave2 (basada en patrón original)
nuevo["llave2"] = f"00000_{hoy.year}{hoy.month:02d}_99999"

# Coherencia de antigüedad
nuevo["antiguedad_meses"] = 0

# Año y mes asociados al nuevo registro
nuevo["anob"] = hoy.year
nuevo["mes"] = hoy.strftime("%B")  # mes en texto

nuevo = nuevo.reset_index(drop=True)
nuevo

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,anob,valor_maximo,valor_medio,valor_bajo,plataforma,ciudad_norm,codigo_mun,departamento,longitud,latitud
0,00000_202511_99999,ESTUDIA YA-TECH GLOBAL,2025-11-22,0,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,2025,0.0,0.0,0.0,ROMBO V1,GIRARDOT,25307.0,Cundinamarca,-74.798201,4.313069

In [54]:
df_final= pd.concat([df_final, nuevo], ignore_index=True)
df_final

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,anob,valor_maximo,valor_medio,valor_bajo,plataforma,ciudad_norm,codigo_mun,departamento,longitud,latitud
0,100046415_202110_13110,ESTUDIA YA-TECH GLOBAL,2021-02-12,56,BOGOTA,1895042,12,Cap. Fijo-Int. vencido,2190800.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,"BOGOTA, D.C.",11001.0,"Bogotá, D.C.",-74.106992,4.649251
1,100094861_202131_13118,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,CONVENIO SENA NACIONAL,1312400,4,Cap. Fijo-Int. vencido,1544000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,MONTELIBANO,23466.0,Córdoba,-75.416818,7.973777
2,100090085_202141_13292,ESTUDIA YA-TECH GLOBAL LINEA BLANCA,2021-02-05,56,CONVENIO INESUR,2589525,4,Cap. Fijo-Int. vencido,3385000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,MOCOA,86001.0,Putumayo,-76.654238,1.151172
3,100082960_202131_13165,ESTUDIA YA-TECH GLOBAL,2021-02-25,56,CONVENIO CONSTRUYENDO FUTURO - CONSFUTUR S.A.S,1307300,6,Cap. Fijo-Int. vencido,1538000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,LA DORADA,17380.0,Cundinamarca,-74.668819,5.460834
4,100083999_202110_13175,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,BOGOTA,2186720,6,Cap. Fijo-Int. vencido,2528000.0,Bajo,...,2021.0,0.0,0.0,0.0,ROMBO V1,"BOGOTA, D.C.",11001.0,"Bogotá, D.C.",-74.106992,4.649251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72612,100229719_202544_90644,LINEA CRÉDITO CUOTA FIJO,2025-10-05,1,BOGOTA,2061160,4,Anualidad Vencida,2493895.0,Bajo,...,2025.0,4496000.0,3459000.0,2421000.0,ROMBO V2,EL CERRITO,76248.0,Valle del Cauca,-76.311972,3.684229
72613,100181306_202517_92383,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,CONVENIO CIADET,1963387,4,Anualidad Vencida,2378868.0,Bajo,...,2025.0,4343000.0,3341000.0,2338000.0,ROMBO V2,JAMUNDI,76364.0,Valle del Cauca,-76.538472,3.258751
72614,100231814_202508_92406,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,BOGOTA,1636250,6,Anualidad Vencida,1994000.0,Bajo,...,2025.0,3719000.0,2861000.0,2002000.0,ROMBO V2,ITAGUI,5360.0,Antioquia,-75.612056,6.175079
72615,100230402_202517_91000,LINEA CRÉDITO CUOTA FIJO,2025-09-20,1,BOGOTA,1710515,6,Anualidad Vencida,2081371.0,Bajo,...,2025.0,5088000.0,3914000.0,2739000.0,ROMBO V2,SANTA ROSA DE CABAL,66682.0,Tolima,-75.623268,4.876271
72616,00000_202511_99999,ESTUDIA YA-TECH GLOBAL,2025-11-22,0,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,2025.0,0.0,0.0,0.0,ROMBO V1,GIRARDOT,25307.0,Cundinamarca,-74.798201,4.313069

In [55]:
df_final[df_final["id_estudiante"] == "00000"].T

                                                                 72616
llave2                                              00000_202511_99999
nombre_linea                                    ESTUDIA YA-TECH GLOBAL
fecha_aprobacion                                            2025-11-22
antiguedad_meses                                                     0
nombre_fondo                                                    BOGOTA
valor_financiacion                                             1569993
cuotas                                                               6
tipo_interes                                    Cap. Fijo-Int. vencido
vr_neto_matricula                                            2173000.0
y_categorica                                                      Alto
fecha_nacimiento                                            1996-03-04
estado_civil                                               SOLTERO (A)
direccion                                          MANZANA E3 # 4M - 4
genero                                                               F
facultad                                FACULTAD DE CCIAS HUMANAS SOCI
programa                                            PSICOLOGIA VIRTUAL
nivel                                                      PROFESIONAL
estado                                                          Activo
tipoestudiante                                          PRIMER INGRESO
sede                                                               VIR
sello                                           TIENE SELLO FINANCIERO
carga                                                   0 A 999999.999
grupo_etnico                                              NO PERTENECE
tipo_discapacidad                                            NO APLICA
nacionalidad                                                  COLOMBIA
mora                                                             False
valor_cuota_inicial                                           277057.5
valor_primera_cuota                                      291181.275667
fecha_de_pago                                                     20.0
validacion_valor_financiado                              162232.558333
detalle_estado_final                                      Desembolsado
id_estudiante                                                    00000
tipo_estudiante                                       Estudiante Nuevo
operacion                                                      Contact
cate                                                  Sello Financiero
subcate                      Tiene Sello Financiero (Aprobado Directo)
cohorte                                                      Cohorte 5
mes                                                           November
cliente                                                     Estudiante
media_score                             Scoring = o > 640  y < o = 720
anob                                                            2025.0
valor_maximo                                                       0.0
valor_medio                                                        0.0
valor_bajo                                                         0.0
plataforma                                                    ROMBO V1
ciudad_norm                                                   GIRARDOT
codigo_mun                                                     25307.0
departamento                                              Cundinamarca
longitud                                                    -74.798201
latitud                                                       4.313069

In [56]:
df_dash= df_final.copy()

In [57]:
# Descargar el archivo final del modelo
df_dash.to_csv('df_dash.csv', index=False, encoding='utf-8-sig')

In [58]:
df_dash.columns

Index(['llave2', 'nombre_linea', 'fecha_aprobacion', 'antiguedad_meses',
       'nombre_fondo', 'valor_financiacion', 'cuotas', 'tipo_interes',
       'vr_neto_matricula', 'y_categorica', 'fecha_nacimiento', 'estado_civil',
       'direccion', 'genero', 'facultad', 'programa', 'nivel', 'estado',
       'tipoestudiante', 'sede', 'sello', 'carga', 'grupo_etnico',
       'tipo_discapacidad', 'nacionalidad', 'mora', 'valor_cuota_inicial',
       'valor_primera_cuota', 'fecha_de_pago', 'validacion_valor_financiado',
       'detalle_estado_final', 'id_estudiante', 'tipo_estudiante', 'operacion',
       'cate', 'subcate', 'cohorte', 'mes', 'cliente', 'media_score', 'anob',
       'valor_maximo', 'valor_medio', 'valor_bajo', 'plataforma',
       'ciudad_norm', 'codigo_mun', 'departamento', 'longitud', 'latitud'],
      dtype='object')

In [59]:
df_modelo.isna().sum()[df_inicial.isna().sum() > 0]

Series([], dtype: int64)

In [60]:
df_modelo.columns

Index(['Llave2', 'Nombre_linea', 'Fecha_aprobacion', 'Antiguedad_meses',
       'Nombre_fondo', 'Valor_financiacion', 'Cuotas', 'Tipo_interes',
       'Vr_neto_matricula', 'Y_categorica', 'IDBANNER', 'FECHA_NACIMIENTO',
       'ESTADO_CIVIL', 'GENERO', 'FACULTAD', 'PROGRAMA', 'NIVEL', 'ESTADO',
       'TIPOESTUDIANTE', 'SEDE', 'SELLO', 'CARGA', 'GRUPO_ETNICO',
       'TIPO_DISCAPACIDAD', 'NACIONALIDAD', 'Mora', 'Valor_cuota_inicial',
       'Valor_primera_cuota', 'fecha de pago', 'Validación valor financiado',
       'Detalle estado final', 'Tipo_estudiante', 'Operación', 'Cate',
       'Subcate', 'Cohorte', 'Mes', 'Cliente', 'Media Score', 'AñoB',
       'VALOR MAXIMO', 'VALOR MEDIO', 'VALOR BAJO', 'Plataforma'],
      dtype='object')

In [61]:
#Estandarizamos los nombres de las columnas
import unicodedata

def estandarizar_columna(col):
    col = unicodedata.normalize('NFKD', col).encode('ascii', 'ignore').decode('utf-8')
    col = col.lower()
    col = col.replace(" ", "_")
    col = col.replace("-", "_").replace("/", "_")
    col = "_".join(part for part in col.split("_") if part)
    return col
df_modelo.columns = [estandarizar_columna(col) for col in df_modelo.columns]

In [62]:
df_modelo.columns

Index(['llave2', 'nombre_linea', 'fecha_aprobacion', 'antiguedad_meses',
       'nombre_fondo', 'valor_financiacion', 'cuotas', 'tipo_interes',
       'vr_neto_matricula', 'y_categorica', 'idbanner', 'fecha_nacimiento',
       'estado_civil', 'genero', 'facultad', 'programa', 'nivel', 'estado',
       'tipoestudiante', 'sede', 'sello', 'carga', 'grupo_etnico',
       'tipo_discapacidad', 'nacionalidad', 'mora', 'valor_cuota_inicial',
       'valor_primera_cuota', 'fecha_de_pago', 'validacion_valor_financiado',
       'detalle_estado_final', 'tipo_estudiante', 'operacion', 'cate',
       'subcate', 'cohorte', 'mes', 'cliente', 'media_score', 'anob',
       'valor_maximo', 'valor_medio', 'valor_bajo', 'plataforma'],
      dtype='object')

In [64]:
llave_objetivo = "100069806_202117_15795"

fila_original = df_modelo[df_modelo["llave2"] == llave_objetivo].copy()
fila_original

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,subcate,cohorte,mes,cliente,media_score,anob,valor_maximo,valor_medio,valor_bajo,plataforma
83,100069806_202117_15795,ESTUDIA YA-TECH GLOBAL,2021-09-20,49,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,Tiene Sello Financiero (Aprobado Directo),Cohorte 5,Septiembre,Estudiante,Scoring = o > 640 y < o = 720,2021.0,0.0,0.0,0.0,ROMBO V1

In [65]:
from datetime import datetime

hoy = datetime.today()

nuevo = fila_original.copy()

# Cambios solicitados
nuevo["fecha_aprobacion"] = hoy.strftime("%Y-%m-%d")
nuevo["id_estudiante"] = "00000"

# Crear nueva llave2 (basada en patrón original)
nuevo["llave2"] = f"00000_{hoy.year}{hoy.month:02d}_99999"

# Coherencia de antigüedad
nuevo["antiguedad_meses"] = 0

# Año y mes asociados al nuevo registro
nuevo["anob"] = hoy.year
nuevo["mes"] = hoy.strftime("%B")  # mes en texto

nuevo = nuevo.reset_index(drop=True)
nuevo

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,cohorte,mes,cliente,media_score,anob,valor_maximo,valor_medio,valor_bajo,plataforma,id_estudiante
0,00000_202511_99999,ESTUDIA YA-TECH GLOBAL,2025-11-22,0,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,Cohorte 5,November,Estudiante,Scoring = o > 640 y < o = 720,2025,0.0,0.0,0.0,ROMBO V1,00000

In [66]:
df_modelo= pd.concat([df_modelo, nuevo], ignore_index=True)
df_modelo

,llave2,nombre_linea,fecha_aprobacion,antiguedad_meses,nombre_fondo,valor_financiacion,cuotas,tipo_interes,vr_neto_matricula,y_categorica,...,cohorte,mes,cliente,media_score,anob,valor_maximo,valor_medio,valor_bajo,plataforma,id_estudiante
0,100046415_202110_13110,ESTUDIA YA-TECH GLOBAL,2021-02-12,56,BOGOTA,1895042,12,Cap. Fijo-Int. vencido,2190800.0,Bajo,...,Cohorte 1,Febrero,Estudiante,Scoring = o > 721,2021.0,0.0,0.0,0.0,ROMBO V1,NaN
1,100094861_202131_13118,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,CONVENIO SENA NACIONAL,1312400,4,Cap. Fijo-Int. vencido,1544000.0,Bajo,...,Cohorte 1,Febrero,Estudiante,Scoring = o > 721,2021.0,0.0,0.0,0.0,ROMBO V1,NaN
2,100090085_202141_13292,ESTUDIA YA-TECH GLOBAL LINEA BLANCA,2021-02-05,56,CONVENIO INESUR,2589525,4,Cap. Fijo-Int. vencido,3385000.0,Bajo,...,Cohorte 1,Febrero,Estudiante,Scoring = o > 401 y < o = 480,2021.0,0.0,0.0,0.0,ROMBO V1,NaN
3,100082960_202131_13165,ESTUDIA YA-TECH GLOBAL,2021-02-25,56,CONVENIO CONSTRUYENDO FUTURO - CONSFUTUR S.A.S,1307300,6,Cap. Fijo-Int. vencido,1538000.0,Bajo,...,Cohorte 1,Febrero,Estudiante,Scoring = o > 561 y < o = 639,2021.0,0.0,0.0,0.0,ROMBO V1,NaN
4,100083999_202110_13175,ESTUDIA YA-TECH GLOBAL,2021-02-15,56,BOGOTA,2186720,6,Cap. Fijo-Int. vencido,2528000.0,Bajo,...,Cohorte 1,Febrero,Estudiante,Scoring = o > 561 y < o = 639,2021.0,0.0,0.0,0.0,ROMBO V1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72288,100229719_202544_90644,LINEA CRÉDITO CUOTA FIJO,2025-10-05,1,BOGOTA,2061160,4,Anualidad Vencida,2493895.0,Bajo,...,Cohorte 4,Septiembre,Estudiante,Scoring = o > 721,2025.0,4496000.0,3459000.0,2421000.0,ROMBO V2,NaN
72289,100181306_202517_92383,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,CONVENIO CIADET,1963387,4,Anualidad Vencida,2378868.0,Bajo,...,Cohorte 5,Octubre,No Estudiante,Scoring = o > 721,2025.0,4343000.0,3341000.0,2338000.0,ROMBO V2,NaN
72290,100231814_202508_92406,LINEA CRÉDITO CUOTA FIJO,2025-10-20,0,BOGOTA,1636250,6,Anualidad Vencida,1994000.0,Bajo,...,Cohorte 5,Octubre,Estudiante,Scoring = o > 721,2025.0,3719000.0,2861000.0,2002000.0,ROMBO V2,NaN
72291,100230402_202517_91000,LINEA CRÉDITO CUOTA FIJO,2025-09-20,1,BOGOTA,1710515,6,Anualidad Vencida,2081371.0,Bajo,...,Cohorte 5,Septiembre,No Estudiante,Scoring = o > 561 y < o = 639,2025.0,5088000.0,3914000.0,2739000.0,ROMBO V2,NaN
72292,00000_202511_99999,ESTUDIA YA-TECH GLOBAL,2025-11-22,0,BOGOTA,1569993,6,Cap. Fijo-Int. vencido,2173000.0,Alto,...,Cohorte 5,November,Estudiante,Scoring = o > 640 y < o = 720,2025.0,0.0,0.0,0.0,ROMBO V1,00000

In [67]:
df_modelo[df_modelo["id_estudiante"] == "00000"].T

                                                                 72292
llave2                                              00000_202511_99999
nombre_linea                                    ESTUDIA YA-TECH GLOBAL
fecha_aprobacion                                            2025-11-22
antiguedad_meses                                                     0
nombre_fondo                                                    BOGOTA
valor_financiacion                                             1569993
cuotas                                                               6
tipo_interes                                    Cap. Fijo-Int. vencido
vr_neto_matricula                                            2173000.0
y_categorica                                                      Alto
idbanner                                                   100069806.0
fecha_nacimiento                                            1996-03-04
estado_civil                                               SOLTERO (A)
genero                                                               F
facultad                                FACULTAD DE CCIAS HUMANAS SOCI
programa                                            PSICOLOGIA VIRTUAL
nivel                                                      PROFESIONAL
estado                                                          Activo
tipoestudiante                                          PRIMER INGRESO
sede                                                               VIR
sello                                           TIENE SELLO FINANCIERO
carga                                                   0 A 999999.999
grupo_etnico                                              NO PERTENECE
tipo_discapacidad                                            NO APLICA
nacionalidad                                                  COLOMBIA
mora                                                             False
valor_cuota_inicial                                           277057.5
valor_primera_cuota                                      291181.275667
fecha_de_pago                                                     20.0
validacion_valor_financiado                              162232.558333
detalle_estado_final                                      Desembolsado
tipo_estudiante                                       Estudiante Nuevo
operacion                                                      Contact
cate                                                  Sello Financiero
subcate                      Tiene Sello Financiero (Aprobado Directo)
cohorte                                                      Cohorte 5
mes                                                           November
cliente                                                     Estudiante
media_score                             Scoring = o > 640  y < o = 720
anob                                                            2025.0
valor_maximo                                                       0.0
valor_medio                                                        0.0
valor_bajo                                                         0.0
plataforma                                                    ROMBO V1
id_estudiante                                                    00000

In [68]:
df_modelo.to_csv('df_modelo_col.csv', index=False, encoding='utf-8-sig')